import tailwindcssAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // shadcn/ui tokens (CSS-variable driven, ver src/styles/global.css).
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "#e7e0ed",
        primary: {
          DEFAULT: "#d0bcff",
          foreground: "#3c0091",
        },
        secondary: {
          DEFAULT: "#4cd7f6",
          foreground: "#003640",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },

        // Design system "Quantum AI Portfolio" (Material 3, exportado desde Stitch).
        background: "#15121b",
        "on-background": "#e7e0ed",
        surface: "#15121b",
        "on-surface": "#e7e0ed",
        "surface-variant": "#37333d",
        "on-surface-variant": "#cbc3d7",
        "surface-dim": "#15121b",
        "surface-bright": "#3b3742",
        "surface-container-lowest": "#0f0d15",
        "surface-container-low": "#1d1a23",
        "surface-container": "#211e27",
        "surface-container-high": "#2c2832",
        "surface-container-highest": "#37333d",
        "surface-tint": "#d0bcff",
        outline: "#958ea0",
        "outline-variant": "#494454",
        "inverse-surface": "#e7e0ed",
        "inverse-on-surface": "#322f39",
        "inverse-primary": "#6d3bd7",
        "on-primary": "#3c0091",
        "primary-container": "#a078ff",
        "on-primary-container": "#340080",
        "primary-fixed": "#e9ddff",
        "on-primary-fixed": "#23005c",
        "primary-fixed-dim": "#d0bcff",
        "on-primary-fixed-variant": "#5516be",
        "on-secondary": "#003640",
        "secondary-container": "#03b5d3",
        "on-secondary-container": "#00424e",
        "secondary-fixed": "#acedff",
        "on-secondary-fixed": "#001f26",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed-variant": "#004e5c",
        tertiary: "#ffb869",
        "on-tertiary": "#482900",
        "tertiary-container": "#ca801e",
        "on-tertiary-container": "#3f2300",
        "tertiary-fixed": "#ffdcbb",
        "on-tertiary-fixed": "#2c1700",
        "tertiary-fixed-dim": "#ffb869",
        "on-tertiary-fixed-variant": "#673d00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-edge": "32px",
        gutter: "24px",
        "section-gap-mobile": "64px",
        base: "8px",
        "section-gap-desktop": "120px",
        "container-max": "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "display-xl": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
